### ISSUE TITLE
Missing NPM images

### ISSUE THREAD

**Issue by jimmyliangacn** [ploigos/ploigos-containers#119]
There are no NPM images in Quay. Nor is there a reference within ploigos-containers. 

There is however, a branch for feature/npm-tools. Can this tested and merged into main and images produced?

**Comment by dwinchell** [comment]
That branch was WIP that never got very far. Honestly we should probably delete it. It doesn't even install npm.

**Comment by dwinchell** [comment]
Looking at that branch some more, it's pretty far behind main ... if someone were to in fact create an npm image I'd recommend they just start from scratch by branching off of main.

**Comment by jimmyliangacn** [comment]
I was pointed to the javascript image which installs nodejs (which in theory also installs npm). I'm testing that out now but running into an issue trying to look for ng. Looking to see if can expand/modify the javascript image or create a new one.

**Comment by jimmyliangacn** [comment]
Did some local testing and the javascript image may support my needs with a few minor updates. Will submit a PR sometime in the coming weeks. Thanks.
